name: ngomna_chat
description: Ngomna Instant Chat - Application de messagerie instantanée
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Navigation
  get: ^4.6.6

  # Google Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.6

  # Flutter Vector Icons
  flutter_vector_icons: ^2.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - assets/fonts/

fonts:
  # Roboto Regular
  - family: Roboto-Regular
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf

  # Roboto Medium
  - family: Roboto-Medium
    fonts:
      - asset: assets/fonts/Roboto-Medium.ttf

  # Roboto SemiBold
  - family: Roboto-SemiBold
    fonts:
      - asset: assets/fonts/Roboto-SemiBold.ttf

  # Roboto Bold
  - family: Roboto-Bold
    fonts:
      - asset: assets/fonts/Roboto-Bold.ttf

  # Roboto ExtraBold
  - family: Roboto-ExtraBold
    fonts:
      - asset: assets/fonts/Roboto-ExtraBold.ttf

  # Rosario Regular
  - family: Rosario-Regular
    fonts:
      - asset: assets/fonts/Rosario-Regular.ttf

  # Rosario Medium
  - family: Rosario-Medium
    fonts:
      - asset: assets/fonts/Rosario-Medium.ttf

  # IMPORTANT: Dire à Flutter de NE PAS chercher sur le web
fallbacks:
  - "Arial"
  - "sans-serif"
